### ISSUE TITLE
cancel API issue on magento 3.2.3

### ISSUE THREAD

**Issue by Fredrik-H-Laastad** [DIBS-Payment-Services/Magento#16]
There seems to be an error with Magento version 3.2.3 

A merchant is reporting that they are experiencing the following error message: 

Strict Standards: Declaration of Dibsfw_Dibsfw_Model_Dibsfw::cancel() should be compatible with Mage_Payment_Model_Method_Abstract::cancel(Varien_Object $payment) in 
/root/app/code/community/Dibsfw/Dibsfw/Model/Dibsfw.php on line 26

please advise.

**Comment by gulzi** [comment]
to me it looks like typo, payment variable should be of Varien_type which was missing in function definition. 
Chanaged from:
public function cancel( $payment ) 

To:
public function cancel( Varien_Object $payment ) (/root/app/code/community/Dibsfw/Dibsfw/Model/Dibsfw.php on line 121)

It do fix the issue but need to test, since  code access to http://tech.dibspayment.com/D2/API/Payment_functions/cancelcgi is not public (connot find it). so need to tested by devs.

fix should be added to next update.
